Verduidelijking + voorbeeld van extra params bij error model.
digipolisantwerpdocumentation/api-requirements pull request #11
Opened 2018-09-03 06:32 UTC by StevenVandenBroeck

2018-09-03 07:07 UTC, PeterClaes commented on README.md
> +    "eventuele_extra_parameters": "custom"     (optioneel, bv een array van validatiefouten)
in het Engels zoals de andere , extra_parameters (eventueel mag weg, wordt aangegeven door de optionaliteit)

2018-09-03 07:16 UTC, PeterClaes commented on README.md
> +-   **Optionele extra parameters** die nuttig zijn voor de API consumer om het probleem te kunnen begrijpen.
Optionele extra info

2018-09-03 07:16 UTC, PeterClaes commented on README.md
extra info

2018-09-03 07:18 UTC, tom-dierckx approved these changes

2018-09-03 07:20 UTC, PeterClaes commented on README.md
> --   Extra parameters die nuttig zijn voor de API consumer om het probleem te kunnen begrijpen.
Optionele extra info die nuttig is voor ...

2018-09-03 07:22 UTC, PeterClaes requested changes
zie comments

2018-09-03 11:35 UTC, PeterClaes commented on README.md
> +In sommige gevallen kan het nuttig zijn om **extra gegevens** mee te geven zodat de consumer beter begrijpt wat het probleem is, zoals bvb bij validatiefouten :
**extra info**

2018-09-03 11:37 UTC, PeterClaes commented on README.md
> +"validation-errors": [
"extraInfo":{"validationErrors": .... : vast attribuut voorzien in root, camelCase gebruiken voor keys

2018-09-03 11:46 UTC, PeterClaes requested changes
zie (aangepaste en opgeslagen :-) ) comments

2018-09-04 13:51 UTC, PeterClaes approved these changes

2018-09-04 13:51 UTC, merged