basepath verder uitgewerkt, alsook een basis voorzien voor postman environment files
digipolisantwerpdocumentation/api-requirements pull request #17
Opened 2019-02-26 11:29 UTC by eriklenaerts

2019-02-28 15:06 UTC, PeterClaes commented on postman-tips.md
> +* Voeg een `host` element toe met `"{{host}}"`. Hier kan je dan as variabele waarde in postman de host naar de API gateway geven.
Hier kan je dan a*l*s variabele ...

2019-02-28 15:08 UTC, PeterClaes commented on postman-tips.md
> +De meeste api's verwachten een variabele voor de apikey en de tenant in de header. Als we deze twee header variabele al toevoegen bij elke operatie, wordt het weeral wat makkelijker:
Als we deze twee header variabele**n** ...

2019-02-28 15:11 UTC, PeterClaes commented on postman-tips.md
> +* definieer de `host`globale variabele met waarde `api-gw.antwerpen.be`
gw url is omgevingsafhankelijk : api-gw-o.antwerpen.be, api-gw-a.antwerpen.be en api-gw-p.antwerpen.be

2019-02-28 15:11 UTC, PeterClaes requested changes
typo's + bemerking GW URL

2019-06-26 12:33 UTC, eriklenaerts commented
Hey P. kijk je nog even na? thnx

2019-06-27 13:25 UTC, merged