Patch 5
digipolisantwerpdocumentation/api-requirements pull request #22
Opened 2019-06-26 12:32 UTC by eriklenaerts

extra tip rond gebruik van default values

2019-06-27 13:32 UTC, PeterClaes commented on postman-tips.md
> +                        "name": "tenant",
De header voor een tenant id en zijn waarde hebben we vastgelegd. Zie : https://github.com/digipolisantwerpdocumentation/api-design-and-patterns/blob/master/patterns/multitenancy.md#tenant-id

2019-06-27 13:33 UTC, PeterClaes requested changes
Zie comment ivm tenant header

2019-08-22 09:43 UTC, PeterClaes commented
@eriklenaerts :aanpassing nodig ivm tenant header (zie andere comment)

2019-09-04 15:37 UTC, eriklenaerts commented
hey @PeterClaes heb de tenant aanpassinge gedaan ;)

2019-09-26 15:14 UTC, PeterClaes approved these changes

2019-09-26 15:14 UTC, merged