Enkele tips om om tips om om te gaan met Date, Datetime, timezone bij API's
digipolisantwerpdocumentation/api-requirements pull request #24
Opened 2019-07-24 10:34 UTC by eriklenaerts

We hebben tijdens een project enkele ervaringen opgedaan, dit waren onze conclusies. Zien jullie die ook zo? Anayway, zou handig zijn voor andere die dezelfde vragen er rond hebben ;)

2019-09-02 15:24 UTC, PeterClaes commented on README.md
> +> RFC3339 volgt de ISO 8601 standaard maar heeft enkele optimamisaties voor het internet en machine to machine communicatie. Bijgevolg is deze ideaal voor REST API's)
optimamisaties ? :-)

2019-09-02 15:27 UTC, PeterClaes commented on README.md
> +    * Gebruik de zulu tijdsnotatie om UTC weer te geven "2012-01-01T00:00:00Z". Door die "Z" weten we dat we UTC tijd bedoelen. "2012-01-01T00:00:00" kan evengoed een tijd zijn zonder een UTC offset.
Op het TA overleg is beslist om toch met tijdzone als voorkeur formaat te gebruiken (Zulu mag ook) . Het kan nuttig zijn in sommige systemen om te weten tot welke tijdzone een aanbieder behoort (bv om agendasystemen ofzo te ontwerpen). Er moet dan wel worden verduidelijkt dat de tijdsindicatie de 'lokale' tijd is van de aanbieder (Je kan altijd de Zulu time dan berekenen)

2019-09-02 15:28 UTC, PeterClaes requested changes
Zie comments --> belangrijkste bemerking : tijdzone notatie toch behouden als voorkeur

2019-09-04 11:21 UTC, eriklenaerts commented
hey @PeterClaes heb de gevraagde changes doorgevoerd

2019-09-26 15:22 UTC, PeterClaes approved these changes

2019-09-26 15:23 UTC, merged